os: linux
dist: focal

language: python

services:
  - docker

install:
  - docker-compose -f test/docker-compose.test.yml -p brainzutils_py3_test build

script:
  - docker-compose -f test/docker-compose.test.yml -p brainzutils_test up -d redis
  - travis_wait docker-compose -f test/docker-compose.test.yml -p brainzutils_test run --rm test
      dockerize
      -wait tcp://redis:6379 -timeout 10s
      dockerize
      -wait tcp://musicbrainz_db:5432 -timeout 600s
      pytest
  - docker-compose -f test/docker-compose.test.yml -p brainzutils_test down
